### PR TITLE
class changed to abstract

### PR DESCRIPTION
**Pull request by Yousha**
Use `abstract` instead of using constructor with `throw`.

### CODE REVIEW

**Comment by nisrulz** [comment]
@Yousha can you please explain your PR and why would I want to make my classes abstract.

**Comment by Yousha** [comment]
To prevent instantiation of class, instead of making public constructor with `Throw`.

1- One way to bypass the restriction is to use **reflections**!
2- AS a rule, the reason for making a constructor private is to CONTROL or limit instantiation,  not to prevent instantiation.
3- If it's a nested class, you can access it from the enclosing class...

> An abstract class is a class that is declared abstract—it may or may not include abstract methods. **Abstract classes cannot be instantiated**, but they can be subclassed.
http://docs.oracle.com/javase/tutorial/java/IandI/abstract.html

**Comment by nisrulz** [comment]
@Yousha Well `private` constructor is in place to prevent instantiation in my library.

Here is some explanation

>Defining a constructor with the private modifier says that only the native class (as in the class in which the private constructor is defined) is allowed to create an instance of the class, and no other caller is permitted to do so. There are two possible reasons why one would want to use a private constructor – the first is that you don’t want any objects of your class to be created at all, and the second is that you only want objects to be created internally – as in only created in your class.

Which in my case is exactly what I want to do. I only want the objects be instantiated internal to the library and only only be referenced statically. This Library contains Utility classes which are in general always created as statics in applications. I have just put them under one library for me to be able to access them easily in multiple projects. 

With that said , I only want that people should access them statically.

**Comment by Yousha** [comment]
> With that said , I only want that people should access them statically.

People can still access them statically by using `abstract class`.

But as you want... :)

**Pull request closed without merging**
